baseURL = 'https://pragmatic-reviews.github.io/hugo-site/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
publishDir = 'docs'

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About us'
  url = '/hugo-site/about/'
[[menu.main]]
  identifier = 'posts'
  name = 'Articles'
  url = '/hugo-site/posts/'
