baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
publishDir = 'docs'

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About us'
  url = '/about/'
[[menu.main]]
  identifier = 'posts'
  name = 'Articles'
  url = '/posts/'
